# Use official Python slim image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
COPY . .

# Expose the port FastAPI runs on
EXPOSE 8000

# Create DB on container build
RUN python -c "import database; from database import Base, engine; import models; Base.metadata.create_all(bind=engine)"

# Start FastAPI server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
